name: MultiPurposeServer
version: 0.2
description: Makes it possible to use this minecraft server as webserver and tcp server
load: POSTWORLD
author: knokko
main: nl.knokko.multiserver.plugin.ServerPlugin
database: no
depend: []
softdepend: []
loadbefore: []
commands:
  website:
    description: Sends you the address of the website and lets operators manage the website
    useage: /website [reload]
    aliases: [web]